# RDS
spring:
  datasource:
    url: jdbc:mysql://[AWS RDS Endpoint]:3306/study6
    username: admin
    password: [Password]
    driver-class-name: com.mysql.cj.jdbc.Driver
  # hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect